# Generated by Django 4.2.29 on 2026-04-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.SlugField(max_length=100, unique=True)),
                ('place_id', models.CharField(blank=True, max_length=200)),
                ('lat_lng', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('hero_image', models.URLField(max_length=1000)),
                ('title_line1', models.CharField(max_length=100)),
                ('title_line2', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('hero_title_color', models.CharField(blank=True, max_length=100)),
                ('hero_subtitle_color', models.CharField(blank=True, max_length=100)),
                ('hero_title_weight', models.CharField(blank=True, max_length=100)),
                ('metric_text_color', models.CharField(blank=True, max_length=100)),
                ('history_title', models.TextField()),
                ('history_paragraph1', models.TextField()),
                ('history_paragraph2', models.TextField(blank=True)),
                ('history_paragraph3', models.TextField(blank=True)),
                ('history_image1', models.URLField(blank=True, max_length=1000)),
                ('history_image2', models.URLField(blank=True, max_length=1000)),
                ('video_title', models.CharField(blank=True, max_length=200)),
                ('video_subtitle', models.CharField(blank=True, max_length=200)),
                ('youtube_id', models.CharField(blank=True, max_length=50)),
                ('gallery_title', models.CharField(blank=True, max_length=200)),
                ('gallery_subtitle', models.CharField(blank=True, max_length=200)),
                ('gallery_images', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=list)),
                ('theme_text_root', models.CharField(blank=True, max_length=100)),
                ('theme_border_light', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title_line1'],
            },
        ),
    ]
