# Generated by Django 6.0.4 on 2026-04-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritagesite',
            name='type_tag',
            field=models.CharField(blank=True, help_text='e.g. PALACE, FORT, PARK', max_length=50),
        ),
    ]
