# Generated by Django 6.0.4 on 2026-04-29 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_review_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='review',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_reviews', to='sites.heritagesite'),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
